name: "Test Me"

on:
  workflow_dispatch: # trigger the workflow manually

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello World"

  terraform-apply:
    name: "Terraform Apply to GCP"
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.9.2

      # - name: Initialize Terraform
      #   run: terraform init
      #   working-directory: ./infra.gcp-terraform-github-actions/demo

      # - name: Validate Terraform
      #   run: terraform validate
      #   working-directory: ./infra.gcp-terraform-github-actions/demo

      # - name: Generate terraform.tfvars file
      #   run: |
      #     cat << EOF > terraform.tfvars
      #     billing_account_id = "${{ secrets.GCP_TERRAFORM_GITHUB_ACTIONS_BILLING_ACCOUNT_ID }}"
      #     folder_id = "${{ vars.GCP_TERRAFORM_GITHUB_ACTIONS_FOLDER_ID }}"
      #     project_id = "${{ vars.GCP_TERRAFORM_GITHUB_ACTIONS_DEMO_PROJECT_ID }}"
      #     project_name = "${{ vars.GCP_TERRAFORM_GITHUB_ACTIONS_DEMO_PROJECT_NAME }}"
      #     region     = "${{ vars.GCP_TERRAFORM_GITHUB_ACTIONS_REGION }}"
      #     EOF
      #   working-directory: ./infra.gcp-terraform-github-actions/demo

      - name: Auth in GCP
        id: "gcp_auth"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.GCP_TERRAFORM_GITHUB_ACTIONS_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_TERRAFORM_GITHUB_ACTIONS_WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: "Docker login with GCP access token"
        run: |
          echo '${{ steps.gcp_auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io

      # - name: Write Terraform Admin SA key to file
      #   run: |
      #     echo "${{ secrets.GCP_TERRAFORM_GITHUB_ACTIONS_TERRAFORM_ADMIN_SA_KEY }}" | base64 -d > terraform-admin-sa-key.json
      #   working-directory: ./infra.gcp-terraform-github-actions

      # - name: Print first few characters of SA key file
      #   run: |
      #     echo "First few characters of terraform-admin-sa-key.json:"
      #     head -c 100 terraform-admin-sa-key.json
      #   working-directory: ./infra.gcp-terraform-github-actions

      # - name: Plan Terraform
      #   run: terraform plan -out=tfplan
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: "../terraform-admin-sa-key.json"
      #   working-directory: ./infra.gcp-terraform-github-actions/demo

      # - name: Apply Terraform
      #   run: terraform apply -auto-approve tfplan
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: "../terraform-admin-sa-key.json"
      #   working-directory: ./infra.gcp-terraform-github-actions/demo
