name: "Test Me"

on:
  workflow_dispatch: # trigger the workflow manually

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello World"

  terraform-apply:
    name: "Terraform Apply to GCP"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./infra.gcp-terraform-github-actions/demo

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./infra.gcp-terraform-github-actions/demo

      - name: Generate terraform.tfvars file
        run: |
          cat << EOF > terraform.tfvars
          billing_account_id = "${{ secrets.GCP_TERRAFORM_GITHUB_ACTIONS_BILLING_ACCOUNT_ID }}"
          folder_id = "${{ vars.GCP_TERRAFORM_GITHUB_ACTIONS_FOLDER_ID }}"
          project_id = "${{ vars.GCP_TERRAFORM_GITHUB_ACTIONS_DEMO_PROJECT_ID }}"
          project_name = "${{ vars.GCP_TERRAFORM_GITHUB_ACTIONS_DEMO_PROJECT_NAME }}"
          region     = "${{ vars.GCP_TERRAFORM_GITHUB_ACTIONS_REGION }}"
          EOF
        working-directory: ./infra.gcp-terraform-github-actions/demo
